### ISSUE TITLE
Infinite loop some point sets

### ISSUE THREAD

**Issue by Effseeing** [Logismos/concavehull#2]
if (hbl == INVALID_INDEX) {
    std::size_t e = hull_start;
    do {
        if (hull_tri[e] == bl) {
            hull_tri[e] = a;
            break;
        }
        e = hull_next[e];
    } while (e != hull_start);
}
@senhorsolar What is the reason for the infinite loop that occurs for some point sets and how to modify it, thanks!

**Comment by senhorsolar** [comment]
Hey @Quietliz, it's been a while since I looked at this but I plan on updating it soon. The delaunay triangulation was someone else's code and it looks like there's a more up-to-date version of it.

**Comment by senhorsolar** [comment]
Fixed by using updated delaunator implementation
